In [1]:
import pandas as pd
import numpy as np
# import yfinance as yf

In [2]:
df = pd.read_csv('/home/ginger/code/gderiddershanghai/DVA_Team_173/data_full/processed/complete_labelled_dataset.csv')

In [107]:
# carina_fp = '/home/ginger/code/gderiddershanghai/DVA_Team_173/data_full/raw/twitter_data/kaggle/carina_tweets_cleaned.csv'
# kenny_fp = '/home/ginger/code/gderiddershanghai/DVA_Team_173/data_full/raw/twitter_data/kenny/kenny_stock_tweets_labelled.csv'
# big_fp = '/home/ginger/code/gderiddershanghai/DVA_Team_173/data_full/raw/twitter_data/big_twitter/Tweet.csv'
jason_top = '/home/ginger/code/gderiddershanghai/DVA_Team_173/data_full/processed/IEEE/top.csv'
jason_middle = '/home/ginger/code/gderiddershanghai/DVA_Team_173/data_full/processed/IEEE/mid.csv'
jason_bottom = '/home/ginger/code/gderiddershanghai/DVA_Team_173/data_full/processed/IEEE/bottom.csv'

In [108]:
# carina_df = pd.read_csv(carina_fp)
# kenny_df = pd.read_csv(kenny_fp)
# big_df = pd.read_csv(big_fp)
jason_top_df = pd.read_csv(jason_top)
jason_middle_df = pd.read_csv(jason_middle)
jason_bottom_df = pd.read_csv(jason_bottom)

In [47]:
# Index(['Created_at', 'Tweet', 'Stock_ticker', 'Score', 'Source'], dtype='object')

In [109]:
jason_top_df.head(2)

,TWEET,STOCK,DATE,LAST_PRICE,1_DAY_RETURN,2_DAY_RETURN,3_DAY_RETURN,7_DAY_RETURN,PX_VOLUME,VOLATILITY_10D,VOLATILITY_30D,LSTM_POLARITY,TEXTBLOB_POLARITY
0,RT @IndiaHistorypic: 1994::Young @sundarpichai...,Google,31/01/2017,820.19,0.004438,0.030286,0.030286,0.035772,2020180.0,21.549,14.953,-1.0,0.00
1,"RT @Google: ""If you have the feeling that some...",Google,31/01/2017,820.19,0.004438,0.030286,0.030286,0.035772,2020180.0,21.549,14.953,-1.0,-0.55

In [110]:
def change_jason(df):
    df['Created_at'] = df['DATE']
    df['Company_name'] = df['STOCK']
    df['Stock_ticker'] = 99
    df['Tweet'] = df['TWEET']
    df['Score'] = df['TEXTBLOB_POLARITY']
    df['Source'] = 'Jason'
    df = df[['Created_at', 'Tweet', 'Stock_ticker', 'Company_name', 'Score', 'Source']]
    return df

In [111]:
jason_top_df = change_jason(jason_top_df)
jason_middle_df =change_jason(jason_middle_df)
jason_bottom_df = change_jason(jason_bottom_df)

In [112]:
jason_top_df.head()

,Created_at,Tweet,Stock_ticker,Company_name,Score,Source
0,31/01/2017,RT @IndiaHistorypic: 1994::Young @sundarpichai...,99,Google,0.00,Jason
1,31/01/2017,"RT @Google: ""If you have the feeling that some...",99,Google,-0.55,Jason
2,31/01/2017,"RT @IBMWatson: Welcome @Apple, #ACLU, #AAAI, @...",99,Apple,1.00,Jason
3,31/01/2017,RT @ColMorrisDavis: My family owned a @Ford de...,99,Ford,0.00,Jason
4,31/01/2017,RT @ThatBitchFromNJ: Google's sponsored ad for...,99,Google,-0.10,Jason

## Getting names for Carina

In [27]:
# carina_df.head(2)

,Unnamed: 0,Created_at,Tweet,Stock_ticker,Score,Source
0,0,2020-04-09 23:59:51+00:00,@KennyDegu very very little volume. With $10T ...,SPX,-0.637271,Carina
1,1,2020-04-09 23:58:55+00:00,#ES_F achieved Target 2780 closing above 50% #...,SPX,0.919818,Carina

In [9]:
# def get_company_name(ticker):
#     try:
#         stock = yf.Ticker(ticker)
#         return stock.info.get("longName", "Unknown")
#     except Exception:
#         return "Unknown"

In [10]:
# carina_df.head()["Stock_ticker"].apply(get_company_name) # TOOOO FUCKING SLOOOOOOWWWWWW

In [113]:
stock_dic_fp = '/home/ginger/code/gderiddershanghai/DVA_Team_173/data_full/raw/twitter_data/kaggle/sp500.csv'
stock_dic_df = pd.read_csv(stock_dic_fp)

In [114]:
stock_dic_df.head()

  Symbol                 Name       Sector
0    MMM           3M Company  Industrials
1    AOS      A.O. Smith Corp  Industrials
2    ABT  Abbott Laboratories  Health Care
3   ABBV          AbbVie Inc.  Health Care
4   ABMD          ABIOMED Inc  Health Care

In [35]:
# stock_dic_df = stock_dic_df.rename(columns={"Symbol": "Stock_ticker", "Name": "Company_Name"})
# carina_df = carina_df.merge(stock_dic_df, on="Stock_ticker", how="left")

In [43]:
# carina_df = carina_df[~carina_df['Company_Name'].isna()]

In [51]:
# carina_df = carina_df[['Created_at', 'Tweet', 'Stock_ticker', 'Score', 'Source','Company_Name', 'Sector']]

# Merge DF and change the Source of Jason's DF

In [84]:
jason_top_df.shape, jason_middle_df.shape, jason_bottom_df.shape

((187342, 6), (89848, 6), (90622, 6))

In [115]:
jason_df = pd.concat([jason_top_df, jason_middle_df, jason_bottom_df], ignore_index=True)
jason_df.head()

,Created_at,Tweet,Stock_ticker,Company_name,Score,Source
0,31/01/2017,RT @IndiaHistorypic: 1994::Young @sundarpichai...,99,Google,0.00,Jason
1,31/01/2017,"RT @Google: ""If you have the feeling that some...",99,Google,-0.55,Jason
2,31/01/2017,"RT @IBMWatson: Welcome @Apple, #ACLU, #AAAI, @...",99,Apple,1.00,Jason
3,31/01/2017,RT @ColMorrisDavis: My family owned a @Ford de...,99,Ford,0.00,Jason
4,31/01/2017,RT @ThatBitchFromNJ: Google's sponsored ad for...,99,Google,-0.10,Jason

In [116]:
jason_df['Source'] = 'Carina Found https://www.kaggle.com/datasets/thedevastator/tweet-sentiment-s-impact-on-stock-returns'

In [118]:
# make sure we have somewhere to join on
stock_dic_df['Company_name'] = stock_dic_df['Name']

In [119]:
stock_dic_df.head()

  Symbol                 Name       Sector         Company_name
0    MMM           3M Company  Industrials           3M Company
1    AOS      A.O. Smith Corp  Industrials      A.O. Smith Corp
2    ABT  Abbott Laboratories  Health Care  Abbott Laboratories
3   ABBV          AbbVie Inc.  Health Care          AbbVie Inc.
4   ABMD          ABIOMED Inc  Health Care          ABIOMED Inc

In [123]:
jason_df_merged = jason_df.merge(stock_dic_df[["Company_name", 'Sector', 'Symbol']], on="Company_name", how="left" )

In [124]:
jason_df_merged['Company_name'].value_counts().head()

Ford        47907
Facebook    47684
Google      31657
Next        30908
Apple       29160
Name: Company_name, dtype: int64

In [125]:
# Using chat to create a dictionary because I can't fucking find the ticker symbols
tickers = {
    '21CF': None,  # No longer traded, was FOXA before Disney acquired it
    'ASOS': 'ASC.L',  # London Stock Exchange
    'AT&T': 'T',  # NYSE
    'Adobe': 'ADBE',  # NASDAQ
    'Allianz': 'ALV.DE',  # XETRA
    'Amazon': 'AMZN',  # NASDAQ
    'American Express': 'AXP',  # NYSE
    'Apple': 'AAPL',  # NASDAQ
    'AstraZeneca': 'AZN',  # NASDAQ, LSE: AZN.L
    'Audi': 'VOW.DE',  # Part of Volkswagen
    'Aviva': 'AV.L',  # LSE
    'BASF': 'BAS.DE',  # XETRA
    'BMW': 'BMW.DE',  # XETRA
    'BP': 'BP',  # NYSE, LSE: BP.L
    'Bank of America': 'BAC',  # NYSE
    'Bayer': 'BAYN.DE',  # XETRA
    'BlackRock': 'BLK',  # NYSE
    'Boeing': 'BA',  # NYSE
    'Burberry': 'BRBY.L',  # LSE
    'CBS': 'PARA',  # NYSE (Now part of Paramount Global)
    'CVS Health': 'CVS',  # NYSE
    'Cardinal Health': 'CAH',  # NYSE
    'Carrefour': 'CA.PA',  # Euronext Paris
    'Chevron': 'CVX',  # NYSE
    'Cisco': 'CSCO',  # NASDAQ
    'Citigroup': 'C',  # NYSE
    'CocaCola': 'KO',  # NYSE
    'Colgate': 'CL',  # NYSE
    'Comcast': 'CMCSA',  # NASDAQ
    'Costco': 'COST',  # NASDAQ
    'Danone': 'BN.PA',  # Euronext Paris
    'Deutsche Bank': 'DB',  # NYSE
    'Disney': 'DIS',  # NYSE
    'Equinor': 'EQNR',  # NYSE
    'Expedia': 'EXPE',  # NASDAQ
    'Exxon': 'XOM',  # NYSE
    'Facebook': 'META',  # NASDAQ (formerly FB)
    'FedEx': 'FDX',  # NYSE
    'Ford': 'F',  # NYSE
    'GSK': 'GSK',  # NYSE, LSE: GSK.L
    'General Electric': 'GE',  # NYSE
    'Gillette': None,  # Subsidiary of P&G
    'Goldman Sachs': 'GS',  # NYSE
    'Google': 'GOOGL',  # NASDAQ
    'Groupon': 'GRPN',  # NASDAQ
    'H&M': 'HM-B.ST',  # Stockholm Exchange
    'HP': 'HPQ',  # NYSE
    'HSBC': 'HSBC',  # NYSE, LSE: HSBA.L
    'Heineken': 'HEIA.AS',  # Euronext Amsterdam
    'Home Depot': 'HD',  # NYSE
    'Honda': 'HMC',  # NYSE
    'Hyundai': 'HYMTF',  # OTC
    'IBM': 'IBM',  # NYSE
    'Intel': 'INTC',  # NASDAQ
    'JPMorgan': 'JPM',  # NYSE
    'John Deere': 'DE',  # NYSE
    "Kellogg's": 'K',  # NYSE (now split into K and KLG)
    'Kroger': 'KR',  # NYSE
    "L'Oreal": 'OR.PA',  # Euronext Paris
    'Mastercard': 'MA',  # NYSE
    "McDonald's": 'MCD',  # NYSE
    'Microsoft': 'MSFT',  # NASDAQ
    'Morgan Stanley': 'MS',  # NYSE
    'Nestle': 'NESN.S',  # SIX Swiss Exchange
    'Netflix': 'NFLX',  # NASDAQ
    'Next': 'NXT.L',  # LSE
    'Nike': 'NKE',  # NYSE
    'Nissan': '7201.T',  # Tokyo Exchange
    'Oracle': 'ORCL',  # NYSE
    'P&G': 'PG',  # NYSE
    'PayPal': 'PYPL',  # NASDAQ
    'Pepsi': 'PEP',  # NASDAQ
    'Pfizer': 'PFE',  # NYSE
    'Reuters': None,  # Part of Thomson Reuters (NYSE: TRI)
    'Ryanair': 'RYAAY',  # NASDAQ
    'SAP': 'SAP',  # NYSE, XETRA
    'Samsung': '005930.KQ',  # Korea Exchange
    'Santander': 'SAN',  # NYSE, BMAD: SAN.MC
    'Shell': 'SHEL',  # NYSE, LSE
    'Siemens': 'SIE.DE',  # XETRA
    'Sony': 'SONY',  # NYSE
    'Starbucks': 'SBUX',  # NASDAQ
    'TMobile': 'TMUS',  # NASDAQ
    'Tesco': 'TSCO.L',  # LSE
    'Thales': 'HO.PA',  # Euronext Paris
    'Toyota': 'TM',  # NYSE
    'TripAdvisor': 'TRIP',  # NASDAQ
    'UPS': 'UPS',  # NYSE
    'Verizon': 'VZ',  # NYSE
    'Viacom': 'PARA',  # NYSE (now Paramount Global)
    'Visa': 'V',  # NYSE
    'Vodafone': 'VOD',  # NASDAQ, LSE: VOD.L
    'Volkswagen': 'VOW3.DE',  # XETRA
    'Walmart': 'WMT',  # NYSE
    'Wells Fargo': 'WFC',  # NYSE
    'Yahoo': None,  # Acquired by Verizon, no longer publicly traded
    'adidas': 'ADS.DE',  # XETRA
    'bookingcom': 'BKNG',  # NASDAQ (Booking Holdings)
    'eBay': 'EBAY',  # NASDAQ
    'easyJet': 'EZJ.L',  # LSE
    'salesforce.com': 'CRM'  # NYSE
}

In [70]:
# jason_df

In [128]:
jason_df_merged['Stock_ticker'] = jason_df_merged['Company_name'].map(tickers)

In [129]:
jason_df_merged

,Created_at,Tweet,Stock_ticker,Company_name,Score,Source,Sector,Symbol,Stock_Ticker
0,31/01/2017,RT @IndiaHistorypic: 1994::Young @sundarpichai...,GOOGL,Google,0.000000,Carina Found https://www.kaggle.com/datasets/t...,NaN,NaN,GOOGL
1,31/01/2017,"RT @Google: ""If you have the feeling that some...",GOOGL,Google,-0.550000,Carina Found https://www.kaggle.com/datasets/t...,NaN,NaN,GOOGL
2,31/01/2017,"RT @IBMWatson: Welcome @Apple, #ACLU, #AAAI, @...",AAPL,Apple,1.000000,Carina Found https://www.kaggle.com/datasets/t...,NaN,NaN,AAPL
3,31/01/2017,RT @ColMorrisDavis: My family owned a @Ford de...,F,Ford,0.000000,Carina Found https://www.kaggle.com/datasets/t...,NaN,NaN,F
4,31/01/2017,RT @ThatBitchFromNJ: Google's sponsored ad for...,GOOGL,Google,-0.100000,Carina Found https://www.kaggle.com/datasets/t...,NaN,NaN,GOOGL
...,...,...,...,...,...,...,...,...,...
367807,30/09/2018,RT @SyriaArchivist: @ReutersWorld How about Re...,WMT,Walmart,0.250000,Carina Found https://www.kaggle.com/datasets/t...,Consumer Staples,WMT,WMT
367808,30/09/2018,24 Destinations Where You Can Stay\r\r\r\r\r\r...,EBAY,eBay,0.000000,Carina Found https://www.kaggle.com/datasets/t...,NaN,NaN,EBAY
367809,30/09/2018,"RT @DrKanyuira: In Japan, youths in their mid...",HMC,Honda,-0.063889,Carina Found https://www.kaggle.com/datasets/t...,NaN,NaN,HMC
367810,30/09/2018,RT @Spicywienerprod: The #sexy Roxy Cox Follo...,None,Reuters,0.000000,Carina Found https://www.kaggle.com/datasets/t...,NaN,NaN,None
367811,30/09/2018,@KapilSharmaK9 \r\r\r\r\r\r\nWas watching your...,SONY,Sony,0.500000,Carina Found https://www.kaggle.com/datasets/t...,NaN,NaN,SONY

In [130]:
sp500_tickers = [
    'T', 'ADBE', 'AMZN', 'AXP', 'AAPL', 'BAC', 'BA', 'CVS', 'CAH', 'CVX',
    'CSCO', 'C', 'KO', 'CL', 'CMCSA', 'COST', 'DIS', 'XOM', 'META', 'FDX',
    'F', 'GE', 'GS', 'GOOGL', 'GOOG', 'HD', 'IBM', 'INTC', 'JPM', 'KR',
    'MA', 'MCD', 'MSFT', 'MS', 'NFLX', 'NKE', 'ORCL', 'PG', 'PYPL', 'PEP',
    'PFE', 'SBUX', 'TMUS', 'UPS', 'VZ', 'V', 'WMT', 'WFC', 'CRM']

In [87]:
jason_df_merged.shape

(367812, 10)

In [132]:
# only keep snp 500 stocks
jason_df_merged = jason_df_merged[jason_df_merged['Stock_Ticker'].isin(sp500_tickers)]

In [134]:
jason_df_merged.head()

,Created_at,Tweet,Stock_ticker,Company_name,Score,Source,Sector,Symbol,Stock_Ticker
0,31/01/2017,RT @IndiaHistorypic: 1994::Young @sundarpichai...,GOOGL,Google,0.00,Carina Found https://www.kaggle.com/datasets/t...,NaN,NaN,GOOGL
1,31/01/2017,"RT @Google: ""If you have the feeling that some...",GOOGL,Google,-0.55,Carina Found https://www.kaggle.com/datasets/t...,NaN,NaN,GOOGL
2,31/01/2017,"RT @IBMWatson: Welcome @Apple, #ACLU, #AAAI, @...",AAPL,Apple,1.00,Carina Found https://www.kaggle.com/datasets/t...,NaN,NaN,AAPL
3,31/01/2017,RT @ColMorrisDavis: My family owned a @Ford de...,F,Ford,0.00,Carina Found https://www.kaggle.com/datasets/t...,NaN,NaN,F
4,31/01/2017,RT @ThatBitchFromNJ: Google's sponsored ad for...,GOOGL,Google,-0.10,Carina Found https://www.kaggle.com/datasets/t...,NaN,NaN,GOOGL

In [137]:
jason_df_merged = jason_df_merged[['Created_at', 'Tweet', 'Score', 'Source', 'Company_name', 'Stock_Ticker']]

In [139]:
stock_dic_df

,Symbol,Name,Sector,Company_name,Stock_ticker
0,MMM,3M Company,Industrials,3M Company,MMM
1,AOS,A.O. Smith Corp,Industrials,A.O. Smith Corp,AOS
2,ABT,Abbott Laboratories,Health Care,Abbott Laboratories,ABT
3,ABBV,AbbVie Inc.,Health Care,AbbVie Inc.,ABBV
4,ABMD,ABIOMED Inc,Health Care,ABIOMED Inc,ABMD
...,...,...,...,...,...
500,YUM,Yum! Brands Inc,Consumer Discretionary,Yum! Brands Inc,YUM
501,ZBRA,Zebra Technologies,Information Technology,Zebra Technologies,ZBRA
502,ZBH,Zimmer Biomet Holdings,Health Care,Zimmer Biomet Holdings,ZBH
503,ZION,Zions Bancorp,Financials,Zions Bancorp,ZION
504,ZTS,Zoetis,Health Care,Zoetis,ZTS

In [145]:
stock_dic_df['Stock_ticker'] = stock_dic_df['Symbol']
stock_dic_df['Stock_Ticker'] = stock_dic_df['Stock_ticker']
# stock_dic_df['Company_name'] = stock_dic_df['Company_Name']

In [144]:
# jason_df_filtered
jason_df_merged.head()

,Created_at,Tweet,Score,Source,Company_name,Stock_Ticker
0,31/01/2017,RT @IndiaHistorypic: 1994::Young @sundarpichai...,0.00,Carina Found https://www.kaggle.com/datasets/t...,Google,GOOGL
1,31/01/2017,"RT @Google: ""If you have the feeling that some...",-0.55,Carina Found https://www.kaggle.com/datasets/t...,Google,GOOGL
2,31/01/2017,"RT @IBMWatson: Welcome @Apple, #ACLU, #AAAI, @...",1.00,Carina Found https://www.kaggle.com/datasets/t...,Apple,AAPL
3,31/01/2017,RT @ColMorrisDavis: My family owned a @Ford de...,0.00,Carina Found https://www.kaggle.com/datasets/t...,Ford,F
4,31/01/2017,RT @ThatBitchFromNJ: Google's sponsored ad for...,-0.10,Carina Found https://www.kaggle.com/datasets/t...,Google,GOOGL

In [161]:
jason_df_merged

,Created_at,Tweet,Score,Source,Company_name,Stock_Ticker,Company_Name
0,31/01/2017,RT @IndiaHistorypic: 1994::Young @sundarpichai...,0.000000,Carina Found https://www.kaggle.com/datasets/t...,Google,GOOGL,Google
1,31/01/2017,"RT @Google: ""If you have the feeling that some...",-0.550000,Carina Found https://www.kaggle.com/datasets/t...,Google,GOOGL,Google
2,31/01/2017,"RT @IBMWatson: Welcome @Apple, #ACLU, #AAAI, @...",1.000000,Carina Found https://www.kaggle.com/datasets/t...,Apple,AAPL,Apple
3,31/01/2017,RT @ColMorrisDavis: My family owned a @Ford de...,0.000000,Carina Found https://www.kaggle.com/datasets/t...,Ford,F,Ford
4,31/01/2017,RT @ThatBitchFromNJ: Google's sponsored ad for...,-0.100000,Carina Found https://www.kaggle.com/datasets/t...,Google,GOOGL,Google
...,...,...,...,...,...,...,...
367801,30/09/2018,"RT @thebradfordfile: When I'm depressed, I rem...",0.000000,Carina Found https://www.kaggle.com/datasets/t...,Costco,COST,Costco
367803,30/09/2018,RT @NFL: Sony Michel vs. Miami's rush defense?...,0.136364,Carina Found https://www.kaggle.com/datasets/t...,Microsoft,MSFT,Microsoft
367805,30/09/2018,RT @JesseFFerguson: CBS NEWS - \r\r\r\r\r\r\n\...,0.000000,Carina Found https://www.kaggle.com/datasets/t...,McDonald's,MCD,McDonald's
367806,30/09/2018,"RT @DonaldInDenial: So if you’re telkom, MTN a...",0.000000,Carina Found https://www.kaggle.com/datasets/t...,Microsoft,MSFT,Microsoft
367807,30/09/2018,RT @SyriaArchivist: @ReutersWorld How about Re...,0.250000,Carina Found https://www.kaggle.com/datasets/t...,Walmart,WMT,Walmart

In [162]:
jason_df_merged = jason_df_merged.merge(stock_dic_df[['Sector',  'Stock_Ticker']], on="Stock_Ticker", how="left")

In [163]:
jason_df_merged['Company_Name'] = jason_df_merged['Company_name']

In [164]:
jason_df_merged

,Created_at,Tweet,Score,Source,Company_name,Stock_Ticker,Company_Name,Sector
0,31/01/2017,RT @IndiaHistorypic: 1994::Young @sundarpichai...,0.000000,Carina Found https://www.kaggle.com/datasets/t...,Google,GOOGL,Google,Communication Services
1,31/01/2017,"RT @Google: ""If you have the feeling that some...",-0.550000,Carina Found https://www.kaggle.com/datasets/t...,Google,GOOGL,Google,Communication Services
2,31/01/2017,"RT @IBMWatson: Welcome @Apple, #ACLU, #AAAI, @...",1.000000,Carina Found https://www.kaggle.com/datasets/t...,Apple,AAPL,Apple,Information Technology
3,31/01/2017,RT @ColMorrisDavis: My family owned a @Ford de...,0.000000,Carina Found https://www.kaggle.com/datasets/t...,Ford,F,Ford,Consumer Discretionary
4,31/01/2017,RT @ThatBitchFromNJ: Google's sponsored ad for...,-0.100000,Carina Found https://www.kaggle.com/datasets/t...,Google,GOOGL,Google,Communication Services
...,...,...,...,...,...,...,...,...
285150,30/09/2018,"RT @thebradfordfile: When I'm depressed, I rem...",0.000000,Carina Found https://www.kaggle.com/datasets/t...,Costco,COST,Costco,Consumer Staples
285151,30/09/2018,RT @NFL: Sony Michel vs. Miami's rush defense?...,0.136364,Carina Found https://www.kaggle.com/datasets/t...,Microsoft,MSFT,Microsoft,Information Technology
285152,30/09/2018,RT @JesseFFerguson: CBS NEWS - \r\r\r\r\r\r\n\...,0.000000,Carina Found https://www.kaggle.com/datasets/t...,McDonald's,MCD,McDonald's,Consumer Discretionary
285153,30/09/2018,"RT @DonaldInDenial: So if you’re telkom, MTN a...",0.000000,Carina Found https://www.kaggle.com/datasets/t...,Microsoft,MSFT,Microsoft,Information Technology
285154,30/09/2018,RT @SyriaArchivist: @ReutersWorld How about Re...,0.250000,Carina Found https://www.kaggle.com/datasets/t...,Walmart,WMT,Walmart,Consumer Staples

In [165]:
jason_fp = '/home/ginger/code/gderiddershanghai/DVA_Team_173/data_full/processed/kaggle_processed.csv'
jason_df_merged.to_csv(jason_fp)

## merge Kenny, Carina, Jason

In [154]:
kaggle_fp = '/home/ginger/code/gderiddershanghai/DVA_Team_173/data_full/processed/kaggle_processed.csv'
ieee_fp = '/home/ginger/code/gderiddershanghai/DVA_Team_173/data_full/processed/IEEE/processed_labelled_IEEE.csv'
kenny_kaggle_fp = '/home/ginger/code/gderiddershanghai/DVA_Team_173/data_full/raw/twitter_data/kenny/kenny_stock_tweets_labelled.csv'

In [166]:
kaggle_df = pd.read_csv(kaggle_fp)
ieee_df = pd.read_csv(ieee_fp)
kenny_kaggle_df = pd.read_csv(kenny_kaggle_fp)

In [167]:
kaggle_df.head(2)

,Unnamed: 0,Created_at,Tweet,Score,Source,Company_name,Stock_Ticker,Company_Name,Sector
0,0,31/01/2017,RT @IndiaHistorypic: 1994::Young @sundarpichai...,0.00,Carina Found https://www.kaggle.com/datasets/t...,Google,GOOGL,Google,Communication Services
1,1,31/01/2017,"RT @Google: ""If you have the feeling that some...",-0.55,Carina Found https://www.kaggle.com/datasets/t...,Google,GOOGL,Google,Communication Services

In [168]:
ieee_df.head(2)

,Created_at,Tweet,Stock_ticker,Score,Source,Company_Name,Sector
0,2020-04-09 23:58:27+00:00,@Issaquahfunds Hedged our $MSFT position into ...,MSFT,-1.062240,IEEE Dataset https://ieee-dataport.org/open-ac...,Microsoft Corp.,Information Technology
1,2020-04-09 23:57:27+00:00,Pfizer Shares Acquired by Ipswich Investment M...,PFE,0.341477,IEEE Dataset https://ieee-dataport.org/open-ac...,Pfizer Inc.,Health Care

In [169]:
kenny_kaggle_df.sample(2)

,Date,Tweet,Stock Name,Company Name,full_text,predicted_score
58283,2022-04-28 21:22:54+00:00,"$AAPL No guidance, YoY performance for upcomin...",AAPL,Apple Inc.,"$AAPL No guidance, YoY performance for upcomin...",-0.330797
48528,2022-09-01 23:29:40+00:00,Made over $13k today trading $AMZN and $CRM op...,AMZN,"Amazon.com, Inc.",Made over $13k today trading $AMZN and $CRM op...,0.854344

In [170]:
kenny_kaggle_df['Created_at'] = kenny_kaggle_df['Date']
kenny_kaggle_df['Score'] = kenny_kaggle_df['predicted_score']
kenny_kaggle_df['Stock_Ticker'] = kenny_kaggle_df['Stock Name']
kenny_kaggle_df['Company_Name'] = kenny_kaggle_df['Company Name']

In [172]:
kenny_kaggle_df.head(1)

,Date,Tweet,Stock Name,Company Name,full_text,predicted_score,Created_at,Score,Stock_Ticker,Company_Name
0,2022-09-29 23:41:16+00:00,Mainstream media has done an amazing job at br...,TSLA,"Tesla, Inc.",Mainstream media has done an amazing job at br...,0.549933,2022-09-29 23:41:16+00:00,0.549933,TSLA,"Tesla, Inc."

In [174]:
# Fix kenny_kaggle
kenny_kaggle_df = kenny_kaggle_df.merge(stock_dic_df[['Sector',  'Stock_Ticker']], on="Stock_Ticker", how="left")

# Get all the columns the same

In [177]:
target_columns = ['Created_at', 'Tweet', 'Stock_Ticker', 'Company_Name', 'Sector', 'Score', 'Source']

In [179]:
kaggle_df = kaggle_df[target_columns]

### IEEE

In [182]:
ieee_df['Stock_Ticker'] = ieee_df['Stock_ticker']

In [184]:
ieee_df = ieee_df[target_columns]

### kenny

In [189]:
kenny_kaggle_df['Source'] = 'Kenny https://www.kaggle.com/datasets/equinxx/stock-tweets-for-sentiment-analysis-and-prediction'
kenny_kaggle_df = kenny_kaggle_df[target_columns]

In [191]:
merged_df = pd.concat([ieee_df, kaggle_df, kenny_kaggle_df], ignore_index=True)

In [217]:
merged_df = pd.concat([ieee_df, kaggle_df, kenny_kaggle_df], ignore_index=True)

## Check if all stocks are in SnP

In [198]:
merged_df.shape

(526288, 7)

In [197]:
snp_stocks = list(set(stock_dic_df['Symbol']))

In [203]:
merged_df = merged_df[merged_df['Stock_Ticker'].isin(snp_stocks)]

In [ ]:
snp

In [204]:
out_fp = '/home/ginger/code/gderiddershanghai/DVA_Team_173/data_full/processed/merged_three.csv'
merged_df.to_csv(out_fp)

### BIG DF Loading and normalizing

In [207]:
big_fp = '/home/ginger/code/gderiddershanghai/DVA_Team_173/data_full/processed/large_dataset_SCORES.csv'
big_df = pd.read_csv(big_fp)

In [208]:
big_df.shape

(2238329, 7)

In [209]:
big_df['Score']= big_df['predicted_score']

In [215]:
big_df['Company_Name'] = big_df['Company_name']

In [216]:
big_df.sample(1)

,Tweet,Stock_ticker,Company_name,Created_at,Source,full_text,predicted_score,Score,Company_Name
784242,long from here!! $GOOGL,GOOGL,Google Inc,2018-04-26 05:03:08,Large Dataset Ginger https://www.kaggle.com/da...,long from here!! $GOOGL,0.93118,0.93118,Google Inc

In [217]:
sector_classification = {
    'Amazon.com': 'Consumer Discretionary',
    'Google Inc': 'Communication Services',
    'Microsoft': 'Information Technology',
    'Tesla Inc': 'Consumer Discretionary',
    'apple': 'Information Technology'
}

big_df['Sector'] = big_df['Company_Name'].map(sector_classification)

In [221]:
big_df['Stock_Ticker'] = big_df['Stock_ticker']

In [223]:
big_df = big_df[target_columns]

# merge the datasets

In [ ]:
2238329

In [225]:
# big_df = big_df[merged_df.columns]
pd.concat([merged_df, big_df], ignore_index=True)

,Created_at,Tweet,Stock_Ticker,Company_Name,Sector,Score,Source
0,2020-04-09 23:58:27+00:00,@Issaquahfunds Hedged our $MSFT position into ...,MSFT,Microsoft Corp.,Information Technology,-1.062240,IEEE Dataset https://ieee-dataport.org/open-ac...
1,2020-04-09 23:57:27+00:00,Pfizer Shares Acquired by Ipswich Investment M...,PFE,Pfizer Inc.,Health Care,0.341477,IEEE Dataset https://ieee-dataport.org/open-ac...
2,2020-04-09 23:56:58+00:00,RT @TDANetwork: 📽️ #TheWatchList panel assesse...,AAPL,Apple Inc.,Information Technology,-0.530649,IEEE Dataset https://ieee-dataport.org/open-ac...
3,2020-04-09 23:56:25+00:00,I can't stand this #Facebook commercial that k...,FB,Facebook Inc.,Communication Services,-0.972969,IEEE Dataset https://ieee-dataport.org/open-ac...
4,2020-04-09 23:55:40+00:00,Analysts Anticipate Progressive Corp $PGR to A...,PGR,Progressive Corp.,Financials,0.410131,IEEE Dataset https://ieee-dataport.org/open-ac...
...,...,...,...,...,...,...,...
2662016,2019-12-31 23:53:21,In 2020 I may start Tweeting out positive news...,TSLA,Tesla Inc,Consumer Discretionary,0.466505,Large Dataset Ginger https://www.kaggle.com/da...
2662017,2019-12-31 23:54:03,Patiently Waiting for the no twitter sitter tw...,TSLA,Tesla Inc,Consumer Discretionary,-0.010292,Large Dataset Ginger https://www.kaggle.com/da...
2662018,2019-12-31 23:55:37,I don't discriminate. I own both $aapl and $ms...,AAPL,apple,Information Technology,0.620104,Large Dataset Ginger https://www.kaggle.com/da...
2662019,2019-12-31 23:55:37,I don't discriminate. I own both $aapl and $ms...,MSFT,Microsoft,Information Technology,0.620104,Large Dataset Ginger https://www.kaggle.com/da...
2662020,2019-12-31 23:55:53,"$AAPL #patent 10,522,475 Vertical interconnect...",AAPL,apple,Information Technology,0.065466,Large Dataset Ginger https://www.kaggle.com/da...

In [237]:
df = pd.concat([merged_df, big_df], ignore_index=True)

# Using Chat - ensure the date time objects are all the same

In [240]:
# import pandas as pd

# def safe_parse_date(date_string):
#     try:
#         # Try parsing with different formats
#         for fmt in ('%Y-%m-%d %H:%M:%S%z', '%Y-%m-%d %H:%M:%S', '%Y-%m-%d', '%d/%m/%Y', '%m/%d/%Y', '%Y.%m.%d'):
#             try:
#                 return pd.to_datetime(date_string, format=fmt)
#             except ValueError:
#                 continue
        
#         # If none of the above formats work, let pandas try to infer
#         return pd.to_datetime(date_string, infer_datetime_format=True)
#     except:
#         # If all attempts fail, return NaT
#         return pd.NaT

# # Apply the function to the 'Created_at' column
# df['Created_at'] = df['Created_at'].apply(safe_parse_date)

# # Convert to a consistent format (e.g., ISO format)
# df['Created_at'] = df['Created_at'].dt.strftime('%Y-%m-%d %H:%M:%S')

In [244]:
df['Created_at'] = pd.to_datetime(df['Created_at'], infer_datetime_format=True, utc=True)

In [245]:
df.sample(5)

,Created_at,Tweet,Stock_Ticker,Company_Name,Sector,Score,Source
1300083,2018-06-08 02:52:30+00:00,Some money flow knowledge for everyone$NVDA $T...,AMZN,Amazon.com,Consumer Discretionary,0.948105,Large Dataset Ginger https://www.kaggle.com/da...
2633199,2019-12-18 13:54:35+00:00,If 'group stink' was a thing then $AAPL and th...,AAPL,apple,Information Technology,-1.095485,Large Dataset Ginger https://www.kaggle.com/da...
1448491,2018-08-08 01:27:14+00:00,Lol @ all of the $tsla comments I’m seeing on ...,TSLA,Tesla Inc,Consumer Discretionary,0.895474,Large Dataset Ginger https://www.kaggle.com/da...
2553363,2019-11-06 15:59:33+00:00,This is based on an incorrect Electrek article...,TSLA,Tesla Inc,Consumer Discretionary,-0.334026,Large Dataset Ginger https://www.kaggle.com/da...
2115142,2019-04-21 06:27:07+00:00,...but have you driven one bro? Like really br...,TSLA,Tesla Inc,Consumer Discretionary,0.009850,Large Dataset Ginger https://www.kaggle.com/da...

In [ ]:
# df.to_csv('/home/ginger/code/gderiddershanghai/DVA_Team_173/data_full/processed/iteration1.csv')

In [246]:
set(df['Company_Name'])

{'3M Company',
 'A.O. Smith Corp',
 'ABIOMED Inc',
 'AES Corp',
 'AFLAC Inc',
 'AMETEK Inc.',
 'ANSYS',
 'AT&T',
 'AT&T Inc.',
 'AbbVie Inc.',
 'Abbott Laboratories',
 'Accenture plc',
 'Activision Blizzard',
 'Adobe',
 'Adobe Inc.',
 'Advance Auto Parts',
 'Advanced Micro Devices Inc',
 'Advanced Micro Devices, Inc.',
 'Agilent Technologies Inc',
 'Air Products & Chemicals Inc',
 'Akamai Technologies Inc',
 'Alaska Air Group Inc',
 'Albemarle Corp',
 'Alexandria Real Estate Equities',
 'Alexion Pharmaceuticals',
 'Align Technology',
 'Allegion',
 'Alliant Energy Corp',
 'Allstate Corp',
 'Alphabet Inc.',
 'Alphabet Inc. (Class A)',
 'Alphabet Inc. (Class C)',
 'Altria Group Inc',
 'Amazon',
 'Amazon.com',
 'Amazon.com Inc.',
 'Amazon.com, Inc.',
 'Amcor plc',
 'Ameren Corp',
 'American Airlines Group',
 'American Electric Power',
 'American Express',
 'American Express Co',
 'American International Group',
 'American Tower Corp.',
 'American Water Works Company Inc',
 'Ameriprise Financial',
 'AmerisourceBergen Corp',
 'Amgen Inc.',
 'Amphenol Corp',
 'Analog Devices Inc.',
 'Anthem',
 'Aon plc',
 'Apache Corporation',
 'Apartment Investment & Management',
 'Apple',
 'Apple Inc.',
 'Applied Materials Inc.',
 'Aptiv PLC',
 'Archer-Daniels-Midland Co',
 'Arista Networks',
 'Arthur J. Gallagher & Co.',
 'Assurant',
 'Atmos Energy',
 'AutoZone Inc',
 'Autodesk Inc.',
 'Automatic Data Processing',
 'AvalonBay Communities',
 'Avery Dennison Corp',
 'Baker Hughes Co',
 'Ball Corp',
 'Bank of America',
 'Bank of America Corp',
 'Baxter International Inc.',
 'Becton Dickinson',
 'Best Buy Co. Inc.',
 'Bio-Rad Laboratories',
 'Biogen Inc.',
 'BlackRock',
 'Boeing',
 'Boeing Company',
 'Booking Holdings Inc',
 'BorgWarner',
 'Boston Properties',
 'Boston Scientific',
 'Bristol-Myers Squibb',
 'Broadcom Inc.',
 'Broadridge Financial Solutions',
 'C. H. Robinson Worldwide',
 'CBRE Group',
 'CDW',
 'CF Industries Holdings Inc',
 'CIGNA Corp.',
 'CME Group Inc.',
 'CMS Energy',
 'CSX Corp.',
 'CVS Health',
 'Cabot Oil & Gas',
 'Cadence Design Systems',
 'Campbell Soup',
 'Capital One Financial',
 'Cardinal Health',
 'Cardinal Health Inc.',
 'Carmax Inc',
 'Carnival Corp.',
 'Carrier Global',
 'Caterpillar Inc.',
 'Cboe Global Markets',
 'Celanese',
 'Centene Corporation',
 'CenterPoint Energy',
 'CenturyLink Inc',
 'Cerner',
 'Charles Schwab Corporation',
 'Charter Communications',
 'Chevron',
 'Chevron Corp.',
 'Chipotle Mexican Grill',
 'Chubb Limited',
 'Church & Dwight',
 'Cincinnati Financial',
 'Cintas Corporation',
 'Cisco',
 'Cisco Systems',
 'Citigroup',
 'Citigroup Inc.',
 'Citizens Financial Group',
 'Citrix Systems',
 'Coca-Cola Company',
 'CocaCola',
 'Cognizant Technology Solutions',
 'Colgate',
 'Colgate-Palmolive',
 'Comcast',
 'Comcast Corp.',
 'Comerica Inc.',
 'Conagra Brands',
 'Concho Resources',
 'ConocoPhillips',
 'Consolidated Edison',
 'Constellation Brands',
 'Copart Inc',
 'Corning Inc.',
 'Corteva',
 'Costco',
 'Costco Wholesale Corp.',
 'Costco Wholesale Corporation',
 'Coty Inc',
 'Crown Castle International Corp.',
 'Cummins Inc.',
 'D. R. Horton',
 'DTE Energy Co.',
 'DXC Technology',
 'DaVita Inc.',
 'Danaher Corp.',
 'Darden Restaurants',
 'Deere & Co.',
 'Delta Air Lines Inc.',
 'Dentsply Sirona',
 'Devon Energy',
 'DexCom',
 'Diamondback Energy',
 'Digital Realty Trust Inc',
 'Discover Financial Services',
 'Discovery Inc. (Class A)',
 'Discovery Inc. (Class C)',
 'Dish Network',
 'Disney',
 'Dollar General',
 'Dollar Tree',
 'Dominion Energy',
 "Domino's Pizza",
 'Dover Corporation',
 'Dow Inc.',
 'DuPont de Nemours Inc',
 'Duke Energy',
 'Duke Realty Corp',
 'E*Trade',
 'EOG Resources',
 'Eastman Chemical',
 'Eaton Corporation',
 'Ecolab Inc.',
 "Edison Int'l",
 'Edwards Lifesciences',
 'Electronic Arts',
 'Emerson Electric Company',
 'Entergy Corp.',
 'Equifax Inc.',
 'Equinix',
 'Equity Residential',
 'Essex Property Trust Inc.',
 'Estée Lauder Companies',
 'Everest Re Group Ltd.',
 'Evergy',
 'Eversource Energy',
 'Exelon Corp.',
 'Expedia Group',
 'Expeditors',
 'Extra Space Storage',
 'Exxon',
 'Exxon Mobil Corp.',
 'F5 Networks',
 'FLIR Systems',
 'FMC Corporation',
 'Facebook Inc.',
 'Fastenal Co',
 'FedEx',
 'FedEx Corporation',
 'Federal Realty Investment Trust',
 'Fidelity National Information Services',
 'Fifth Third Bancorp',
 'First Republic Bank',
 'FirstEnergy Corp',
 'Fiserv Inc',
 'FleetCor Technologies Inc',
 'Flowserve Corporation',
 'Ford',
 'Ford Motor Company',
 'Fortinet',
 'Fortive Corp',
 'Fortune Brands Home & Security',
 'Fox Corporation (Class A)',
 'Fox Corporation (Class B)',
 'Franklin Resources',
 'Freeport-McMoRan Inc.',
 'Gap Inc.',
 'Garmin Ltd.',
 'Gartner Inc',
 'General Dynamics',
 'General Electric',
 'General Mills',
 'General Motors',
 'Genuine Parts',
 'Gilead Sciences',
 'Global Payments Inc.',
 'Globe Life Inc.',
 'Goldman Sachs',
 'Goldman Sachs Group',
 'Google',
 'Google Inc',
 'Grainger (W.W.) Inc.',
 'H&R Block',
 'HCA Healthcare',
 'HP Inc.',
 'Halliburton Co.',
 'Hanesbrands Inc',
 'Hartford Financial Svc.Gp.',
 'Hasbro Inc.',
 'Healthpeak Properties',
 'Henry Schein',
 'Hess Corporation',
 'Hewlett Packard Enterprise',
 'Hilton Worldwide Holdings Inc',
 'HollyFrontier Corp',
 'Hologic',
 'Home Depot',
 "Honeywell Int'l Inc.",
 'Hormel Foods Corp.',
 'Host Hotels & Resorts',
 'Howmet Aerospace',
 'Humana Inc.',
 'Huntington Bancshares',
 'Huntington Ingalls Industries',
 'IBM',
 'IDEX Corporation',
 'IDEXX Laboratories',
 'IHS Markit Ltd.',
 'IPG Photonics Corp.',
 'IQVIA Holdings Inc.',
 'Illinois Tool Works',
 'Illumina Inc',
 'Incyte',
 'Ingersoll Rand',
 'Intel',
 'Intel Corp.',
 'Intel Corporation',
 'Intercontinental Exchange',
 'International Business Machines',
 'International Flavors & Fragrances',
 'International Paper',
 'Interpublic Group',
 'Intuit Inc.',
 'Intuitive Surgical Inc.',
 'Invesco Ltd.',
 'Iron Mountain Incorporated',
 'J. B. Hunt Transport Services',
 'JM Smucker',
 'JPMorgan',
 'JPMorgan Chase & Co.',
 'Jack Henry & Associates',
 'Jacobs Engineering Group',
 'Johnson & Johnson',
 'Johnson Controls International',
 'Juniper Networks',
 'KLA Corporation',
 'Kansas City Southern',
 'Kellogg Co.',
 'KeyCorp',
 'Keysight Technologies',
 'Kimberly-Clark',
 'Kimco Realty',
 'Kinder Morgan',
 "Kohl's Corp.",
 'Kraft Heinz Co',
 'Kroger',
 'Kroger Co.',
 'L Brands Inc.',
 'LKQ Corporation',
 'Laboratory Corp. of America Holding',
 'Lam Research',
 'Lamb Weston Holdings Inc',
 'Las Vegas Sands',
 'Leggett & Platt',
 'Leidos Holdings',
 'Lennar Corp.',
 'Lilly (Eli) & Co.',
 'Lincoln National',
 'Linde plc',
 'Live Nation Entertainment',
 'Lockheed Martin Corp.',
 'Loews Corp.',
 "Lowe's Cos.",
 'LyondellBasell',
 'M&T Bank Corp.',
 'MGM Resorts International',
 'MSCI Inc',
 'Marathon Oil Corp.',
 'Marathon Petroleum',
 'MarketAxess',
 "Marriott Int'l.",
 'Marsh & McLennan',
 'Martin Marietta Materials',
 'Masco Corp.',
 'Mastercard',
 'Mastercard Inc.',
 'Maxim Integrated Products Inc',
 'McCormick & Co.',
 "McDonald's",
 "McDonald's Corp.",
 'McKesson Corp.',
 'Medtronic plc',
 'Merck & Co.',
 'MetLife Inc.',
 'Mettler Toledo',
 'Microchip Technology',
 'Micron Technology',
 'Microsoft',
 'Microsoft Corp.',
 'Microsoft Corporation',
 'Mid-America Apartments',
 'Mohawk Industries',
 'Molson Coors Beverage Company',
 'Mondelez International',
 'Monster Beverage',
 "Moody's Corp",
 'Morgan Stanley',
 'Motorola Solutions Inc.',
 'Mylan N.V.',
 'NRG Energy',
 'NVR Inc.',
 'Nasdaq Inc.',
 'National Oilwell Varco Inc.',
 'NetApp',
 'Netflix',
 'Netflix Inc.',
 'Netflix, Inc.',
 'Newell Brands',
 'Newmont Corporation',
 'News Corp. Class A',
 'News Corp. Class B',
 'NextEra Energy',
 'NiSource Inc.',
 'Nielsen Holdings',
 'Nike',
 'Nike Inc.',
 'Noble Energy',
 'Norfolk Southern Corp.',
 'Northern Trust Corp.',
 'Northrop Grumman',
 'Northrop Grumman Corporation',
 'NortonLifeLock',
 'Norwegian Cruise Line Holdings',
 'Nucor Corp.',
 'Nvidia Corporation',
 "O'Reilly Automotive",
 'ONEOK',
 'Occidental Petroleum',
 'Old Dominion Freight Line',
 'Omnicom Group',
 'Oracle',
 'Oracle Corp.',
 'Otis Worldwide',
 'P&G',
 'PACCAR Inc.',
 'PNC Financial Services',
 'PPG Industries',
 'PPL Corp.',
 'PVH Corp.',
 'Packaging Corporation of America',
 'Parker-Hannifin',
 'PayPal',
 'PayPal Holdings, Inc.',
 'Paychex Inc.',
 'Paycom',
 'Pentair plc',
 "People's United Financial",
 'Pepsi',
 'PepsiCo Inc.',
 'PerkinElmer',
 'Perrigo',
 'Pfizer',
 'Pfizer Inc.',
 'Philip Morris International',
 'Phillips 66',
 'Pinnacle West Capital',
 'Pioneer Natural Resources',
 'Principal Financial Group',
 'Procter & Gamble',
 'Procter & Gamble Company',
 'Progressive Corp.',
 'Prologis',
 'Prudential Financial',
 'Public Service Enterprise Group (PSEG)',
 'Public Storage',
 'PulteGroup',
 'QUALCOMM Inc.',
 'Qorvo',
 'Quanta Services Inc.',
 'Quest Diagnostics',
 'Ralph Lauren Corporation',
 'Raymond James Financial Inc.',
 'Raytheon Technologies',
 'Realty Income Corporation',
 'Regency Centers Corporation',
 'Regeneron Pharmaceuticals',
 'Regions Financial Corp.',
 'Republic Services Inc',
 'ResMed',
 'Robert Half International',
 'Rockwell Automation Inc.',
 'Rollins Inc.',
 'Roper Technologies',
 'Ross Stores',
 'Royal Caribbean Group',
 'S&P Global Inc.',
 'SBA Communications',
 'SL Green Realty',
 'STERIS plc',
 'SVB Financial',
 'Salesforce, Inc.',
 'Salesforce.com',
 'Schlumberger Ltd.',
 'Seagate Technology',
 'Sealed Air',
 'Sempra Energy',
 'ServiceNow',
 'Sherwin-Williams',
 'Simon Property Group Inc',
 'Skyworks Solutions',
 'Snap-on',
 'Southern Company',
 'Southwest Airlines',
 'Stanley Black & Decker',
 'Starbucks',
 'Starbucks Corp.',
 'State Street Corp.',
 'Stryker Corp.',
 'Synchrony Financial',
 'Synopsys Inc.',
 'Sysco Corp.',
 'T-Mobile US',
 'T. Rowe Price Group',
 'TE Connectivity Ltd.',
 'TJX Companies Inc.',
 'TMobile',
 'Take-Two Interactive',
 'Tapestry Inc.',
 'Target Corp.',
 'TechnipFMC',
 'Teledyne Technologies',
 'Teleflex',
 'Tesla Inc',
 'Texas Instruments',
 'Textron Inc.',
 'The Bank of New York Mellon',
 'The Boeing Company',
 'The Clorox Company',
 'The Coca-Cola Company',
 'The Cooper Companies',
 'The Hershey Company',
 'The Mosaic Company',
 'The Travelers Companies Inc.',
 'The Walt Disney Company',
 'Thermo Fisher Scientific',
 'Tiffany & Co.',
 'Tractor Supply Company',
 'Trane Technologies plc',
 'TransDigm Group',
 'Truist Financial',
 'Twitter Inc.',
 'Tyler Technologies',
 'Tyson Foods',
 'U.S. Bancorp',
 'UDR Inc.',
 'UPS',
 'Ulta Beauty',
 'Under Armour (Class A)',
 'Under Armour (Class C)',
 'Union Pacific Corp',
 'United Airlines Holdings',
 'United Health Group Inc.',
 'United Parcel Service',
 'United Rentals Inc.',
 'Universal Health Services',
 'Unum Group',
 'VF Corporation',
 'Valero Energy',
 'Varian Medical Systems',
 'Ventas Inc',
 'Verisign Inc.',
 'Verisk Analytics',
 'Verizon',
 'Verizon Communications',
 'Verizon Communications Inc.',
 'Vertex Pharmaceuticals Inc',
 'ViacomCBS',
 'Visa',
 'Visa Inc.',
 'Vornado Realty Trust',
 'Vulcan Materials',
 'W. R. Berkley Corporation',
 'WEC Energy Group',
 'Wabtec Corporation',
 'Walgreens Boots Alliance',
 'Walmart',
 'Waste Management Inc.',
 'Waters Corporation',
 'Wells Fargo',
 'Welltower Inc.',
 'West Pharmaceutical Services',
 'WestRock',
 'Western Digital',
 'Western Union Co',
 'Weyerhaeuser',
 'Whirlpool Corp.',
 'Williams Companies',
 'Willis Towers Watson',
 'Wynn Resorts Ltd',
 'Xcel Energy Inc',
 'Xerox',
 'Xilinx',
 'Xylem Inc.',
 'Yum! Brands Inc',
 'Zebra Technologies',
 'Zimmer Biomet Holdings',
 'Zions Bancorp',
 'Zoetis',
 'apple',
 'eBay Inc.',
 'salesforce.com'}

In [ ]:
# switching to chat GPT

In [317]:
import re

synonyms = {
    # AT&T
    'at&t': 'AT&T Inc.',
    'at&t inc': 'AT&T Inc.',

    # Adobe
    'adobe': 'Adobe Inc.',
    'adobe inc': 'Adobe Inc.',

    # Amazon
    'amazon': 'Amazon.com Inc.',
    'amazoncom': 'Amazon.com Inc.',
    'amazoncom inc': 'Amazon.com Inc.',

    # American Express
    'american express': 'American Express Co',
    'american express co': 'American Express Co',

    # Apple
    'apple': 'Apple Inc.',
    'apple inc': 'Apple Inc.',

    # Bank of America
    'bank of america': 'Bank of America Corp',
    'bank of america corp': 'Bank of America Corp',

    # Boeing
    'boeing': 'The Boeing Company',
    'boeing company': 'The Boeing Company',
    'the boeing company': 'The Boeing Company',

    # Cardinal Health
    'cardinal health': 'Cardinal Health Inc.',
    'cardinal health inc': 'Cardinal Health Inc.',

    # Chevron
    'chevron': 'Chevron Corp.',
    'chevron corp': 'Chevron Corp.',

    # Cisco
    'cisco': 'Cisco Systems',
    'cisco systems': 'Cisco Systems',

    # Citigroup
    'citigroup': 'Citigroup Inc.',
    'citigroup inc': 'Citigroup Inc.',

    # Coca-Cola
    'cocacola': 'The Coca-Cola Company',
    'coca-cola company': 'The Coca-Cola Company',
    'the coca-cola company': 'The Coca-Cola Company',

    # Colgate
    'colgate': 'Colgate-Palmolive',
    'colgate-palmolive': 'Colgate-Palmolive',

    # Comcast
    'comcast': 'Comcast Corp.',
    'comcast corp': 'Comcast Corp.',

    # Costco
    'costco': 'Costco Wholesale Corporation',
    'costco wholesale corp': 'Costco Wholesale Corporation',
    'costco wholesale corporation': 'Costco Wholesale Corporation',

    # Disney
    'disney': 'The Walt Disney Company',
    'the walt disney company': 'The Walt Disney Company',

    # Exxon
    'exxon': 'Exxon Mobil Corp.',
    'exxon mobil corp': 'Exxon Mobil Corp.',

    # Facebook (aka Meta)
    'facebook': "Meta Platforms, Inc.",
    'facebook inc': "Meta Platforms, Inc.",
    'meta': "Meta Platforms, Inc.",
    'meta platforms': "Meta Platforms, Inc.",
    'meta platforms inc': "Meta Platforms, Inc.",

    # FedEx
    'fedex': 'FedEx Corporation',
    'fedex corporation': 'FedEx Corporation',

    # Ford
    'ford': 'Ford Motor Company',
    'ford motor company': 'Ford Motor Company',

    # Goldman Sachs
    'goldman sachs': 'Goldman Sachs Group',
    'goldman sachs group': 'Goldman Sachs Group',

    # Google / Alphabet – unify under Alphabet Inc.
    'google': 'Alphabet Inc.',
    'google inc': 'Alphabet Inc.',
    'alphabet inc class a': 'Alphabet Inc.',
    'alphabet inc class c': 'Alphabet Inc.',
    'alphabet inc (class a)': 'Alphabet Inc.',
    'alphabet inc (class c)': 'Alphabet Inc.',

    # IBM
    'ibm': 'International Business Machines',
    'international business machines': 'International Business Machines',

    # Intel
    'intel': 'Intel Corporation',
    'intel corp': 'Intel Corporation',
    'intel corporation': 'Intel Corporation',

    # JPMorgan
    'jpmorgan': 'JPMorgan Chase & Co.',
    'jpmorgan chase & co': 'JPMorgan Chase & Co.',

    # Kroger
    'kroger': 'Kroger Co.',
    'kroger co': 'Kroger Co.',

    # Mastercard
    'mastercard': 'Mastercard Inc.',
    'mastercard inc': 'Mastercard Inc.',

    # McDonald's
    "mcdonald's": "McDonald's Corp.",
    "mcdonald's corp": "McDonald's Corp.",

    # Microsoft
    'microsoft': 'Microsoft Corporation',
    'microsoft corp': 'Microsoft Corporation',
    'microsoft corporation': 'Microsoft Corporation',

    # Netflix
    'netflix': 'Netflix Inc.',
    'netflix inc': 'Netflix Inc.',

    # Nike
    'nike': 'Nike Inc.',
    'nike inc': 'Nike Inc.',

    # Oracle
    'oracle': 'Oracle Corp.',
    'oracle corp': 'Oracle Corp.',

    # Procter & Gamble
    'p&g': 'Procter & Gamble Company',
    'procter & gamble': 'Procter & Gamble Company',
    'procter & gamble company': 'Procter & Gamble Company',
    # Coca-Cola
    'coca cola': 'The Coca-Cola Company',
    'coca-cola': 'The Coca-Cola Company',
    'coca-cola company': 'The Coca-Cola Company',
    'cocacola': 'The Coca-Cola Company',
    'cocacola company': 'The Coca-Cola Company',
    'the coca-cola company': 'The Coca-Cola Company',

    # Merck
    'merck': 'Merck & Co.',
    'merck & co': 'Merck & Co.',
    'merck & co.': 'Merck & Co.',
    # Pepsi
    'pepsi': 'PepsiCo Inc.',
    'pepsico inc': 'PepsiCo Inc.',

    # Pfizer
    'pfizer': 'Pfizer Inc.',
    'pfizer inc': 'Pfizer Inc.',

    # Salesforce
    'salesforce': 'Salesforce, Inc.',
    'salesforcecom': 'Salesforce, Inc.',
    'salesforce.com': 'Salesforce, Inc.',
    'salesforce, inc.': 'Salesforce, Inc.',

    # Starbucks
    'starbucks': 'Starbucks Corp.',
    'starbucks corp': 'Starbucks Corp.',

    # T-Mobile
    'tmobile': 'T-Mobile US',

    # Tesla
    'tesla': 'Tesla, Inc.',
    'tesla inc': 'Tesla, Inc.',
    'tesla, inc': 'Tesla, Inc.',

    # UPS
    'ups': 'United Parcel Service',
    'united parcel service': 'United Parcel Service',

    # Verizon
    'verizon': 'Verizon Communications Inc.',
    'verizon communications': 'Verizon Communications Inc.',
    'verizon communications inc': 'Verizon Communications Inc.',

    # Visa
    'visa': 'Visa Inc.',
    'visa inc': 'Visa Inc.',

    # AMD
    'advanced micro devices inc': 'Advanced Micro Devices, Inc.',
    'amd': 'Advanced Micro Devices, Inc.',

    # Discovery
    'discovery inc': 'Discovery Inc.',
    'discovery inc (class a)': 'Discovery Inc.',
    'discovery inc (class c)': 'Discovery Inc.',

    # Marathon
    'marathon oil corp': 'Marathon Oil Corp.',
    'marathon petroleum': 'Marathon Petroleum',

    # News Corp
    'news corp class a': 'News Corp.',
    'news corp class b': 'News Corp.',

    # Northrop Grumman
    'northrop grumman': 'Northrop Grumman Corporation',
    'northrop grumman corporation': 'Northrop Grumman Corporation',

    # PayPal
    'paypal': 'PayPal Holdings, Inc.',
    'paypal holdings inc': 'PayPal Holdings, Inc.',

    # Under Armour
    'under armour': 'Under Armour',
    'under armour (class a)': 'Under Armour',
    'under armour (class c)': 'Under Armour',

    # American Tower
    'american tower corp.': 'American Tower Corporation',
    'american tower corporation': 'American Tower Corporation',

    # S&P Global
    's&p global': 'S&P Global Inc.',
    's&p global inc.': 'S&P Global Inc.',

    # Hershey
    'hershey company': 'The Hershey Company',
    'the hershey company': 'The Hershey Company',

    # Meta (Future proofing)
    'meta platforms inc.': "Meta Platforms, Inc.",
    'meta platforms inc': "Meta Platforms, Inc.",
}


def consolidate_company_name(company_name: str) -> str:
    """
    Return a canonical version of the company_name if it matches
    a known synonym, otherwise return the name as-is.
    """
    # Convert to lowercase, remove commas and periods, etc. (except & or apostrophes).
    normalized = re.sub(r'[.,]', '', company_name.strip().lower())

    # Look up in synonyms dictionary
    return synonyms.get(normalized, company_name)

In [ ]:
# ---------------------------------------------------------------------------------------------
df['Consolidated_Company_Name'] = df['Company_Name'].apply(consolidate_company_name)

/tmp/ipykernel_26361/2195429778.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['Consolidated_Company_Name'] = df_filtered['Company_Name'].apply(consolidate_company_name)

In [284]:
len(set(df['Consolidated_Company_Name']))

499

In [285]:

ticker_synonyms = {
    'GOOG': 'GOOGL',    # unify GOOG to GOOGL
    'FB': 'META'        # unify FB to META
    # etc. add more if needed
}

def consolidate_ticker(ticker: str) -> str:
    """
    Return a canonical ticker if it matches a known duplicate,
    otherwise return the original ticker.
    """
    return ticker_synonyms.get(ticker, ticker)

# Create a new column with consolidated tickers
df['Consolidated_Ticker'] = df['Stock_Ticker'].apply(consolidate_ticker)

In [286]:
company_counts = df['Consolidated_Company_Name'].value_counts()
# company_counts

In [287]:
filtered_companies = company_counts[company_counts > 888].index
df_filtered = df[df['Consolidated_Company_Name'].isin(filtered_companies)]
len(set(df_filtered['Consolidated_Company_Name']))

40

In [288]:
sorted(filtered_companies)

['AT&T Inc.',
 'Advanced Micro Devices, Inc.',
 'Alphabet Inc.',
 'Amazon.com Inc.',
 'Apple Inc.',
 'Bank of America Corp',
 'Chevron Corp.',
 'Cisco Systems',
 'Comcast Corp.',
 'Costco Wholesale Corporation',
 'Exxon Mobil Corp.',
 'Ford Motor Company',
 'Home Depot',
 'Intel Corporation',
 'International Business Machines',
 'JPMorgan Chase & Co.',
 'Johnson & Johnson',
 'Kroger Co.',
 'Mastercard Inc.',
 "McDonald's Corp.",
 'Merck & Co.',
 'Meta Platforms, Inc.',
 'Microsoft Corporation',
 'Netflix Inc.',
 'Nike Inc.',
 'Oracle Corp.',
 'PayPal Holdings, Inc.',
 'PepsiCo Inc.',
 'Pfizer Inc.',
 'Procter & Gamble Company',
 'Starbucks Corp.',
 'Tesla, Inc.',
 'The Boeing Company',
 'The Coca-Cola Company',
 'The Walt Disney Company',
 'United Health Group Inc.',
 'United Parcel Service',
 'Verizon Communications Inc.',
 'Visa Inc.',
 'Walmart']

In [319]:
df_filtered

,Created_at,Tweet,Stock_Ticker,Company_Name,Sector,Score,Source,Consolidated_Company_Name,Consolidated_Ticker,GICS_Sub_Industry
0,2020-04-09 23:58:27+00:00,@Issaquahfunds Hedged our $MSFT position into ...,MSFT,Microsoft Corp.,Information Technology,-1.062240,IEEE Dataset https://ieee-dataport.org/open-ac...,Microsoft Corporation,MSFT,Systems Software
1,2020-04-09 23:57:27+00:00,Pfizer Shares Acquired by Ipswich Investment M...,PFE,Pfizer Inc.,Health Care,0.341477,IEEE Dataset https://ieee-dataport.org/open-ac...,Pfizer Inc.,PFE,Pharmaceuticals
2,2020-04-09 23:56:58+00:00,RT @TDANetwork: 📽️ #TheWatchList panel assesse...,AAPL,Apple Inc.,Information Technology,-0.530649,IEEE Dataset https://ieee-dataport.org/open-ac...,Apple Inc.,AAPL,"Technology Hardware, Storage & Peripherals"
3,2020-04-09 23:56:25+00:00,I can't stand this #Facebook commercial that k...,FB,Facebook Inc.,Communication Services,-0.972969,IEEE Dataset https://ieee-dataport.org/open-ac...,"Meta Platforms, Inc.",META,Interactive Media & Services
4,2020-04-09 23:55:05+00:00,$AAPL 4h/1h\n\nSometimes these wedges break hi...,AAPL,Apple Inc.,Information Technology,0.561125,IEEE Dataset https://ieee-dataport.org/open-ac...,Apple Inc.,AAPL,"Technology Hardware, Storage & Peripherals"
...,...,...,...,...,...,...,...,...,...,...
2539439,2019-12-31 23:53:21+00:00,In 2020 I may start Tweeting out positive news...,TSLA,Tesla Inc,Consumer Discretionary,0.466505,Large Dataset Ginger https://www.kaggle.com/da...,"Tesla, Inc.",TSLA,Automobile Manufacturers
2539440,2019-12-31 23:54:03+00:00,Patiently Waiting for the no twitter sitter tw...,TSLA,Tesla Inc,Consumer Discretionary,-0.010292,Large Dataset Ginger https://www.kaggle.com/da...,"Tesla, Inc.",TSLA,Automobile Manufacturers
2539441,2019-12-31 23:55:37+00:00,I don't discriminate. I own both $aapl and $ms...,AAPL,apple,Information Technology,0.620104,Large Dataset Ginger https://www.kaggle.com/da...,Apple Inc.,AAPL,"Technology Hardware, Storage & Peripherals"
2539442,2019-12-31 23:55:37+00:00,I don't discriminate. I own both $aapl and $ms...,MSFT,Microsoft,Information Technology,0.620104,Large Dataset Ginger https://www.kaggle.com/da...,Microsoft Corporation,MSFT,Systems Software
2539443,2019-12-31 23:55:53+00:00,"$AAPL #patent 10,522,475 Vertical interconnect...",AAPL,apple,Information Technology,0.065466,Large Dataset Ginger https://www.kaggle.com/da...,Apple Inc.,AAPL,"Technology Hardware, Storage & Peripherals"

In [303]:
# df_filtered.drop_duplicates(subset=['Created_at','Tweet', 'Consolidated_Company_Name', 'Score'], inplace=True)

/tmp/ipykernel_26361/2619418983.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered.drop_duplicates(subset=['Created_at','Tweet', 'Consolidated_Company_Name', 'Score'], inplace=True)

In [305]:
df_filtered.reset_index(drop=True, inplace=True)

In [331]:
df_filtered.groupby('Source').agg({'Created_at': 'count'})

                                                    Created_at
Source
Carina Found https://www.kaggle.com/datasets/th...      157748
IEEE Dataset https://ieee-dataport.org/open-acc...      139742
Kenny https://www.kaggle.com/datasets/equinxx/s...       25617
Large Dataset Ginger https://www.kaggle.com/dat...     2216335

In [336]:
df_filtered['Created_at'].isna().sum()

2

In [337]:
df_filtered.sort_values(by='Created_at')

,Created_at,Tweet,Stock_Ticker,Company_Name,Sector,Score,Source,Consolidated_Company_Name,Consolidated_Ticker,GICS_Sub_Industry
323107,2017-01-29 00:01:11+00:00,Google and Yahoo are dodging warrants after #M...,MSFT,Microsoft,Information Technology,-0.355956,Large Dataset Ginger https://www.kaggle.com/da...,Microsoft Corporation,MSFT,Systems Software
323108,2017-01-29 00:01:48+00:00,"Apple, #Microsoft and Uber help staff stranded...",MSFT,Microsoft,Information Technology,-0.286559,Large Dataset Ginger https://www.kaggle.com/da...,Microsoft Corporation,MSFT,Systems Software
323109,2017-01-29 00:02:25+00:00,Didn't notice suppliers stock tanked? Tesla ju...,TSLA,Tesla Inc,Consumer Discretionary,-0.021860,Large Dataset Ginger https://www.kaggle.com/da...,"Tesla, Inc.",TSLA,Automobile Manufacturers
323110,2017-01-29 00:02:26+00:00,#Google adds more editing capabilities to Docs...,GOOG,Google Inc,Communication Services,0.294692,Large Dataset Ginger https://www.kaggle.com/da...,Alphabet Inc.,GOOGL,Interactive Media & Services
323111,2017-01-29 00:06:08+00:00,"#Microsoft, HP Team Up For Social Impact Hacka...",MSFT,Microsoft,Information Technology,-0.017772,Large Dataset Ginger https://www.kaggle.com/da...,Microsoft Corporation,MSFT,Systems Software
...,...,...,...,...,...,...,...,...,...,...
305668,2022-09-29 22:40:47+00:00,A group of lawmakers led by Sen. Elizabeth War...,AMZN,"Amazon.com, Inc.",Consumer Discretionary,-0.071448,Kenny https://www.kaggle.com/datasets/equinxx/...,Amazon.com Inc.,AMZN,Internet & Direct Marketing Retail
297490,2022-09-29 22:40:47+00:00,A group of lawmakers led by Sen. Elizabeth War...,MSFT,Microsoft Corporation,Information Technology,-0.071448,Kenny https://www.kaggle.com/datasets/equinxx/...,Microsoft Corporation,MSFT,Systems Software
322264,2022-09-29 22:55:15+00:00,High quality businesses such as $ADBE $GOOGL $...,PYPL,"PayPal Holdings, Inc.",Information Technology,0.951840,Kenny https://www.kaggle.com/datasets/equinxx/...,"PayPal Holdings, Inc.",PYPL,Data Processing & Outsourced Services
2059968,NaT,when will you start writing about $TSLA laggin...,TSLA,Tesla Inc,Consumer Discretionary,-0.169000,Large Dataset Ginger https://www.kaggle.com/da...,"Tesla, Inc.",TSLA,Automobile Manufacturers
2228232,NaT,‘Trading Strategies: Over 1400 companies repor...,AAPL,apple,Information Technology,0.006816,Large Dataset Ginger https://www.kaggle.com/da...,Apple Inc.,AAPL,"Technology Hardware, Storage & Peripherals"

In [320]:
gics_sub_industry_map = {
    "AT&T Inc.": "Integrated Telecommunication Services",
    "Adobe Inc.": "Application Software",
    "Advanced Micro Devices Inc": "Semiconductors",
    "Air Products & Chemicals Inc": "Industrial Gases",
    "Alphabet Inc.": "Interactive Media & Services",
    "Amazon.com Inc.": "Internet & Direct Marketing Retail",
    "Apple Inc.": "Technology Hardware, Storage & Peripherals",
    "Bank of America Corp": "Diversified Banks",
    "Boeing Company": "Aerospace & Defense",
    "Broadcom Inc.": "Semiconductors",
    "Carnival Corp.": "Hotels, Resorts & Cruise Lines",
    "Caterpillar Inc.": "Construction Machinery & Heavy Trucks",
    "Chevron Corp.": "Integrated Oil & Gas",
    "Cisco Systems": "Communications Equipment",
    "Citigroup Inc.": "Diversified Banks",
    "Coca-Cola Company": "Soft Drinks",
    "Comcast Corp.": "Cable & Satellite",
    "Costco Wholesale Corp.": "Hypermarkets & Super Centers",
    "Dow Inc.": "Commodity Chemicals",
    "Edwards Lifesciences": "Health Care Equipment",
    "Eversource Energy": "Electric Utilities",
    "Exxon Mobil Corp.": "Integrated Oil & Gas",
    "Facebook Inc.": "Interactive Media & Services",
    "FedEx Corporation": "Air Freight & Logistics",
    "Ford Motor Company": "Automobile Manufacturers",
    "Goldman Sachs Group": "Investment Banking & Brokerage",
    "Home Depot": "Home Improvement Retail",
    "Intel Corp.": "Semiconductors",
    "International Business Machines": "IT Consulting & Other Services",
    "JPMorgan Chase & Co.": "Diversified Banks",
    "Johnson & Johnson": "Pharmaceuticals",
    "Kroger Co.": "Food Retail",
    "Mastercard Inc.": "Data Processing & Outsourced Services",
    "McDonald's Corp.": "Restaurants",
    "Microsoft Corp.": "Systems Software",
    "Morgan Stanley": "Investment Banking & Brokerage",
    "Netflix Inc.": "Movies & Entertainment",
    "Newmont Corporation": "Gold",
    "Nike Inc.": "Footwear",
    "Nvidia Corporation": "Semiconductors",
    "Oracle Corp.": "Systems Software",
    "PayPal": "Data Processing & Outsourced Services",
    "PepsiCo Inc.": "Soft Drinks",
    "Pfizer Inc.": "Pharmaceuticals",
    "Procter & Gamble": "Household Products",
    "Starbucks Corp.": "Restaurants",
    "T-Mobile US": "Wireless Telecommunication Services",
    "Tesla, Inc.": "Automobile Manufacturers",
    "The Bank of New York Mellon": "Asset Management & Custody Banks",
    "The Walt Disney Company": "Movies & Entertainment",
    "Twitter Inc.": "Interactive Media & Services",
    "United Health Group Inc.": "Managed Health Care",
    "United Parcel Service": "Air Freight & Logistics",
    "Verizon Communications": "Integrated Telecommunication Services",
    "Visa Inc.": "Data Processing & Outsourced Services",
    "Walmart": "Hypermarkets & Super Centers",
    "Wells Fargo": "Diversified Banks",
        "AT&T Inc.": "Integrated Telecommunication Services",
    "Adobe Inc.": "Application Software",
    "Advanced Micro Devices, Inc.": "Semiconductors",
    "Alphabet Inc.": "Interactive Media & Services",
    "Amazon.com Inc.": "Internet & Direct Marketing Retail",
    "Apple Inc.": "Technology Hardware, Storage & Peripherals",
    "Bank of America Corp": "Diversified Banks",
    "The Boeing Company": "Aerospace & Defense",
    "Chevron Corp.": "Integrated Oil & Gas",
    "Cisco Systems": "Communications Equipment",
    "Coca-Cola Company": "Soft Drinks",
    "Comcast Corp.": "Cable & Satellite",
    "Costco Wholesale Corporation": "Hypermarkets & Super Centers",
    "Exxon Mobil Corp.": "Integrated Oil & Gas",
    "Meta Platforms, Inc.": "Interactive Media & Services",  # was Facebook Inc.
    "Ford Motor Company": "Automobile Manufacturers",
    "Home Depot": "Home Improvement Retail",
    "Intel Corporation": "Semiconductors",
    "International Business Machines": "IT Consulting & Other Services",
    "JPMorgan Chase & Co.": "Diversified Banks",
    "Johnson & Johnson": "Pharmaceuticals",
    "Kroger Co.": "Food Retail",

    "Mastercard Inc.": "Data Processing & Outsourced Services",
    "The Coca-Cola Company": "Soft Drinks",
    "McDonald's Corp.": "Restaurants",
    "Microsoft Corporation": "Systems Software",
    "Netflix Inc.": "Movies & Entertainment",
    "Nike Inc.": "Footwear",
    "Oracle Corp.": "Systems Software",
     "Merck & Co.": "Pharmaceuticals",
    "PayPal Holdings, Inc.": "Data Processing & Outsourced Services",
    "PepsiCo Inc.": "Soft Drinks",
    "Pfizer Inc.": "Pharmaceuticals",
    "Procter & Gamble Company": "Household Products",
    "Starbucks Corp.": "Restaurants",
    "T-Mobile US": "Wireless Telecommunication Services",
    "Tesla, Inc.": "Automobile Manufacturers",
    "The Walt Disney Company": "Movies & Entertainment",
    "UnitedHealth Group Inc.": "Managed Health Care",  # corrected name
    "United Parcel Service": "Air Freight & Logistics",
    "Verizon Communications Inc.": "Integrated Telecommunication Services",
    "Visa Inc.": "Data Processing & Outsourced Services",
    "Walmart": "Hypermarkets & Super Centers"
}

In [321]:
df_filtered["GICS_Sub_Industry"] = df_filtered["Consolidated_Company_Name"].map(gics_sub_industry_map).fillna("Unknown")

/tmp/ipykernel_26361/2377444709.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered["GICS_Sub_Industry"] = df_filtered["Consolidated_Company_Name"].map(gics_sub_industry_map).fillna("Unknown")

In [322]:
set(df_filtered[df_filtered['GICS_Sub_Industry']=='Unknown']['Company_Name'])

set()

In [324]:
df_filtered.to_csv('/home/ginger/code/gderiddershanghai/DVA_Team_173/data_full/processed/complete_labelled_dataset.csv', index=False)

In [323]:
# df_filtered["Created_at"] = pd.to_datetime(df_filtered["Created_at"])

In [290]:
df_filtered.to_csv('/home/ginger/code/gderiddershanghai/DVA_Team_173/data_full/processed/iteration3.csv')

In [302]:
l = ['Chevron Corp.',
 'Cisco Systems',
 'Citigroup Inc.',
 'Coca-Cola Company',
 'Comcast Corp.',
 'Costco Wholesale Corp.',
 'Dow Inc.',
 'Edwards Lifesciences',
 'Eversource Energy',
 'Exxon Mobil Corp.',
 'Facebook Inc.',
 'FedEx Corporation',
 # 'Ford Motor Company',
 'Goldman Sachs Group']

In [325]:
df_filtered['Consolidated_Company_Name'].value_counts()

Tesla, Inc.                        820419
Apple Inc.                         601150
Amazon.com Inc.                    456058
Alphabet Inc.                      282704
Microsoft Corporation              198507
Ford Motor Company                  28807
The Walt Disney Company             21980
Meta Platforms, Inc.                18118
Nike Inc.                           17565
Netflix Inc.                        14610
Intel Corporation                    6377
JPMorgan Chase & Co.                 6109
Procter & Gamble Company             5310
AT&T Inc.                            4926
Starbucks Corp.                      4319
Walmart                              3800
PayPal Holdings, Inc.                3559
Bank of America Corp                 3257
Pfizer Inc.                          2959
Visa Inc.                            2920
Exxon Mobil Corp.                    2841
Johnson & Johnson                    2820
Advanced Micro Devices, Inc.         2691
PepsiCo Inc.                         2648
McDonald's Corp.                     2501
Verizon Communications Inc.          2276
The Coca-Cola Company                2042
The Boeing Company                   1951
Mastercard Inc.                      1891
Merck & Co.                          1878
United Health Group Inc.             1784
Home Depot                           1632
Comcast Corp.                        1568
International Business Machines      1437
Costco Wholesale Corporation         1185
Chevron Corp.                        1134
Oracle Corp.                         1070
United Parcel Service                1042
Cisco Systems                         922
Kroger Co.                            677
Name: Consolidated_Company_Name, dtype: int64

In [339]:
len(set(df_filtered['Consolidated_Company_Name']))

40

In [338]:
df_filtered

,Created_at,Tweet,Stock_Ticker,Company_Name,Sector,Score,Source,Consolidated_Company_Name,Consolidated_Ticker,GICS_Sub_Industry
0,2020-04-09 23:58:27+00:00,@Issaquahfunds Hedged our $MSFT position into ...,MSFT,Microsoft Corp.,Information Technology,-1.062240,IEEE Dataset https://ieee-dataport.org/open-ac...,Microsoft Corporation,MSFT,Systems Software
1,2020-04-09 23:57:27+00:00,Pfizer Shares Acquired by Ipswich Investment M...,PFE,Pfizer Inc.,Health Care,0.341477,IEEE Dataset https://ieee-dataport.org/open-ac...,Pfizer Inc.,PFE,Pharmaceuticals
2,2020-04-09 23:56:58+00:00,RT @TDANetwork: 📽️ #TheWatchList panel assesse...,AAPL,Apple Inc.,Information Technology,-0.530649,IEEE Dataset https://ieee-dataport.org/open-ac...,Apple Inc.,AAPL,"Technology Hardware, Storage & Peripherals"
3,2020-04-09 23:56:25+00:00,I can't stand this #Facebook commercial that k...,FB,Facebook Inc.,Communication Services,-0.972969,IEEE Dataset https://ieee-dataport.org/open-ac...,"Meta Platforms, Inc.",META,Interactive Media & Services
4,2020-04-09 23:55:05+00:00,$AAPL 4h/1h\n\nSometimes these wedges break hi...,AAPL,Apple Inc.,Information Technology,0.561125,IEEE Dataset https://ieee-dataport.org/open-ac...,Apple Inc.,AAPL,"Technology Hardware, Storage & Peripherals"
...,...,...,...,...,...,...,...,...,...,...
2539439,2019-12-31 23:53:21+00:00,In 2020 I may start Tweeting out positive news...,TSLA,Tesla Inc,Consumer Discretionary,0.466505,Large Dataset Ginger https://www.kaggle.com/da...,"Tesla, Inc.",TSLA,Automobile Manufacturers
2539440,2019-12-31 23:54:03+00:00,Patiently Waiting for the no twitter sitter tw...,TSLA,Tesla Inc,Consumer Discretionary,-0.010292,Large Dataset Ginger https://www.kaggle.com/da...,"Tesla, Inc.",TSLA,Automobile Manufacturers
2539441,2019-12-31 23:55:37+00:00,I don't discriminate. I own both $aapl and $ms...,AAPL,apple,Information Technology,0.620104,Large Dataset Ginger https://www.kaggle.com/da...,Apple Inc.,AAPL,"Technology Hardware, Storage & Peripherals"
2539442,2019-12-31 23:55:37+00:00,I don't discriminate. I own both $aapl and $ms...,MSFT,Microsoft,Information Technology,0.620104,Large Dataset Ginger https://www.kaggle.com/da...,Microsoft Corporation,MSFT,Systems Software
2539443,2019-12-31 23:55:53+00:00,"$AAPL #patent 10,522,475 Vertical interconnect...",AAPL,apple,Information Technology,0.065466,Large Dataset Ginger https://www.kaggle.com/da...,Apple Inc.,AAPL,"Technology Hardware, Storage & Peripherals"

In [346]:
df_filtered.groupby(['Sector','GICS_Sub_Industry'])[['Tweet','Score']].count()

                                                                    Tweet  \
Sector                 GICS_Sub_Industry
Communication Services Cable & Satellite                             1568
                       Integrated Telecommunication Services         7202
                       Interactive Media & Services                300822
                       Movies & Entertainment                       36590
Consumer Discretionary Automobile Manufacturers                    849226
                       Footwear                                     17565
                       Home Improvement Retail                       1632
                       Internet & Direct Marketing Retail          456058
                       Restaurants                                   6820
Consumer Staples       Food Retail                                    677
                       Household Products                            5310
                       Hypermarkets & Super Centers                  4985
                       Soft Drinks                                   4690
Energy                 Integrated Oil & Gas                          3975
Financials             Diversified Banks                             9366
Health Care            Managed Health Care                           1784
                       Pharmaceuticals                               7657
Industrials            Aerospace & Defense                           1951
                       Air Freight & Logistics                       1042
Information Technology Communications Equipment                       922
                       Data Processing & Outsourced Services         8370
                       IT Consulting & Other Services                1437
                       Semiconductors                                9068
                       Systems Software                            199577
                       Technology Hardware, Storage & Peripherals  601150

                                                                    Score
Sector                 GICS_Sub_Industry
Communication Services Cable & Satellite                             1568
                       Integrated Telecommunication Services         7202
                       Interactive Media & Services                300822
                       Movies & Entertainment                       36590
Consumer Discretionary Automobile Manufacturers                    849226
                       Footwear                                     17565
                       Home Improvement Retail                       1632
                       Internet & Direct Marketing Retail          456058
                       Restaurants                                   6820
Consumer Staples       Food Retail                                    677
                       Household Products                            5310
                       Hypermarkets & Super Centers                  4985
                       Soft Drinks                                   4690
Energy                 Integrated Oil & Gas                          3975
Financials             Diversified Banks                             9366
Health Care            Managed Health Care                           1784
                       Pharmaceuticals                               7657
Industrials            Aerospace & Defense                           1951
                       Air Freight & Logistics                       1042
Information Technology Communications Equipment                       922
                       Data Processing & Outsourced Services         8370
                       IT Consulting & Other Services                1437
                       Semiconductors                                9068
                       Systems Software                            199577
                       Technology Hardware, Storage & Peripherals  601150